### PR TITLE
Change `position: fixed` to `position: absolute` fixes #21

### LINKED ISSUE #21: Capture pages that have fixed position footers
Currently the application has a buffer for capturing the top of the screen in order to try and not repeat fixed position content in the header. There is nothing to handle this issue with footers.

Example pages with this problem:
-   http://www.designboom.com/design/interview-with-graphic-designer-gareth-hague-06-23-2014/
-   https://www.grafik.net/category/talent/kathy-lam (some other issues that might be tough to stop on this one)

### PR DESCRIPTION
**Pull request by UziTech**
Change `position: fixed` to `position: absolute` and back after screen capture

### CODE REVIEW

**Comment by mrcoles** [comment]
hrm… have you tried this on many pages and seen if anything scary happens? Since fixed and position both do not affect page flow, it seems like this approach would be pretty promising. I’ll have to give it a try when I get a chance. If this were a configurable setting by the user I’d be happy to launch it as disabled by default so people could test it for a while before we make it big-time.

**Comment by UziTech** [comment]
It isn't perfect. If the element is fixed to the bottom it shows up on the first snapshot at the bottom instead of the bottom of the picture. And if the element is a child or a `position: relative` element it doesn't look correct. But it is better that showing up on every snapshot.

**Comment by UziTech** [comment]
It might be better to hide every fixed element instead of setting them to `position: absolute` and showing them at the end.

**Comment by fboja** [comment]
Just to add to this (since I ran into a similar issue), you should fetch the computed styles, as elements might not have explicit `position` set.

**Pull request closed without merging**
