### PR TITLE
Add timestamp to file names of screenshots

### PR DESCRIPTION
**Pull request by HetIsNiels**
Discussion about the pull request:
https://github.com/mrcoles/full-page-screen-capture-chrome-extension/issues/25#issuecomment-76381757

### CODE REVIEW

**Comment by mrcoles** [comment]
Cool, looks good—I didn’t know about `Date.now()`. I suppose my head is stuck supporting old browsers, but no worry with an extension :+1:

**Comment by mrcoles** [comment]
I’ll try to get around to uploading the change to the store this weekend.

**Comment by d2s** [comment]
This is great, thanks for the fix. :+1:

**Comment by mrcoles** [comment]
sorry for the delay… but finally publishing it along with another fix to the popup where it was previously not opening all the way. Thanks for the PR!

**Pull request closed without merging**
